qubole/qds-sdk-py

bin/qds.py
qds_sdk/commands.py

You can now do something like this:
```
qds.py hivecmd run --print-logs --query 'show tables'
```
and it will print the logs to the stderr, in addition to printing the results to stdout.
PS: We need a rewrite of the SDK - it's getting too messy. :-(

new: usr: zendesk-626: Option to print command logs to stderr when using 'run' action.

---

bin/qds.py
qds_sdk/cluster.py
tests/test_cluster.py

Addressed the comments in pull request #91 and opening on against unreleased branch.

new: dev: Add support for ClusterManage Command

---

.travis.yml
qds_sdk/connection.py

This change adds a total of 3 retries for all get requests to avoid failures due to intermittent network issues.

retry logic for get requests

---

qds_sdk/commands.py

signal.SIGQUIT throws an unsupported error under Windows. This PR adresses it.

fix: SDK310 - remove unsupported SIGQUIT in Windows

---

bin/qds.py
qds_sdk/commands.py
tests/test_command.py

- Added `list` method to Command base class
- Added parser as per params mentioned in [REST API for Command](https://docs.qubole.com/en/latest/rest-api/command_api/view-command-history.html)
- Added tests

chg: dev: SDK-285: Add list functionality to Command to view command history

---

bin/qds.py
qds_sdk/cluster.py
qds_sdk/clusterv2.py
tests/test_cluster.py
tests/test_clusterv2.py

- Added page and per_page option to Cluster
- Added page and per_page option to ClusterV2
- Fixed a bug with Cluster#list method where providing state param results in `TypeError: string indices must be integers`

chg: dev: SDK-330: Add page and per-page option to Cluster and ClusterV2

---

bin/qds.py
qds_sdk/cluster.py
qds_sdk/engine.py
tests/test_cluster.py
tests/test_clusterv2.py

* Add enable_rubix option in engine.py to enable Rubix for a cluster.

Added option to enable rubix in the sdk

---

qds_sdk/commands.py

Caused by block reads chopping multibyte utf-8 sequences in half
Because of the 8192 bytes read block size, a utf-8 character can possibly be cut in two, causing the block to be invalid utf-8.
Fixed by not decoding the block. Instead encode the delimiter and do the replace operation with bytes instead of str.

fixes #175. utf-8 errors in Python 3. 

---

qds_sdk/dbtaps.py

for qds.py command line, the port option although available was not being passed to `DbTap.create` and edit methods, passed them as and when required.

SDK-344 Enable use of port argument for DbTaps

---

qds_sdk/commands.py

I have faced an issue when passing NamedTemporaryFile instance to get_results().
It silently skipped writing, which is very bad.
So to avoid this, commentary 'Can this happen? Don't know what's the right thing to do in this case.' and 'pass' should be replaced with 'raise ValueError()'.

Add exception instead of "pass" to avoid silently skipping of write

---

qds_sdk/cloud/azure_cloud.py
qds_sdk/clusterv2.py
tests/test_clusterv2.py

- Added `resource_group_name` to `cloud_config` to override default account level configs.
- Added `disable_cluster_pause`, `paused_cluster_timeout_mins`, `disable_autoscale_node_pause`, `paused_autoscale_node_timeout_mins` to `cluster_info` to support start-stop changes for Azure

chg: dev: SDK-345: Add custom resource group and start-stop related params for Azure clusters

---

qds_sdk/commands.py

This includes 2 changes:
1. Set boto config to use sigv4 when connecting to s3
2. Set default endpoint for boto connection when endpoint returned is None from Qubole

SDK-354 Default to S3 Signature Version V4

---

.travis.yml

Ubuntu Version got updated by default for Travis CI Builds. Since we hadn't fixed the Ubuntu version our pipelines started using the latest 16.XX version which didn't have python 2.6 and python 3.3

Fix Pipeline by Pinning Ubuntu Version

---

.travis.yml
requirements.txt
setup.py

Security scans are showing CRLF injection vulnerabilities in the older versions of requests and urllib3.  
included unittests pass and manual spot testing of examples in the README.rst succeed.

updating requests and urllib3

---

.deepsource.toml
.travis.yml

Added changes in travis ci to send coverage report to deepsource, https://deepsource.io/docs/analyzers/test-coverage.html#examples

DeepSource PR check and send cov-report to DeepSource

---

qds_sdk/connection.py

Adding Qubole-Trace-Id support for api calls

SDK-375: Add Qubole Trace_id support

---

qds_sdk/connection.py

We often see cases when Airflow Jobs fail because the polling API returns a 500 Response. This change adds retries to all get calls when a 500 Response is returned as a result of heavy load on Qubole's Webapp.

SDK-383: Add Retries to all Get requests in case of 500 Response

---

qds_sdk/engine.py
tests/test_clusterv2.py

SDK-392 - add Mlflow support to qds-sdk repo

---

qds_sdk/connection.py

We have seen issues where Qubole API returns 404 HTML response from Nginx and the call fails with resource not found error with retries not kicking in.
Added change to check if it is a proper JSON Response first if it isn't it means that the response came directly from NGINX and didn't reach the web application. Raising Server Error in such cases so that retries can kick in and avoid intermittent issues.

Validate a JSON response before checking response code

---

qds_sdk/connection.py

Added the following Changes:
1. Rename MyAdapter to RequestAdapter
2. Revert last change of checking non-JSON response first
3. Retry on all error status codes for GET requests

Retry all Errors in Case of Get Request

---

bin/qds.py
qds_sdk/connection.py
qds_sdk/exception.py
qds_sdk/qubole.py

Making 503 response code a retryable exception for all HTTP requests.

new:dev:SDK-386_improvement: Changing retry conditions for 503 response

---

qds_sdk/engine.py
tests/test_clusterv2.py

fix: dev: SDK-397: add dbtap config for mlflow cluster

---

qds_sdk/commands.py
tests/test_command.py

Usage: qds.py --token '<token>' --url <url> jupyternotebookcmd submit --path <path> --cluster-label <label> --arguments '{"arg1": "test_without_upload"}' --skip-upload-to-source
Giving the option --skip-upload-to-source would execute the notebook but not overwrite the source notebook with the result notebook of execution.

SDK-404: Add --skip-upload-to-source option in JupyterNotebookCommand

---

setup.py

Added a check to upgrade inflection only if Python version >= 3.5.
- Inflection 0.4.0 release has dropped support for python version <3.5.

SDK-401: Fix inflection version upgrade on basis of python version

---

bin/qds.py
qds_sdk/connection.py
qds_sdk/qubole.py
tests/test_connection.py

Updating number of retries to 7 so as to honor the last known retry criteria

fix:dev:SDK-386:Updating number of retries

---

qds_sdk/commands.py
tests/test_command.py

Airflow does not support boolean flags. Thus, we are removing '--skip-upload-to-source' option in JupyterNotebookCommand and adding '--upload-to-source' option.
The valid arguments to this option include 'True' and 'False'. Passing any other value would raise a ParseError.

SDK-407, JUPY-884: Add '--upload-to-source' param for JupyterNotebookCommand
